name: Latest blog post workflow with fallback

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme-with-fallback:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check URL status
        id: check_url
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://blog.beucismis.org/posts/index.xml)
          echo "status_code=$STATUS_CODE" >> "$GITHUB_OUTPUT"
          echo "STATUS_CODE=$STATUS_CODE" >> "$GITHUB_ENV"
      - name: Fetch and save feed
        if: steps.check_url.outputs.status_code == '200'
        run: curl -o temp-feeds.xml https://blog.beucismis.org/posts/index.xml
      - name: Setup git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Update this repo's TEMPLATE.md with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          readme_path: "TEMPLATE.md"
          max_post_count: 10
          feed_list: "${{ env.STATUS_CODE == '200' && 'https://blog.beucismis.org/posts/index.xml' || 'temp-feeds.xml' }}"
          date_format: "d mmm yyyy"
          template: "- $date - <a href='$url'>$title</a> <br/>"
      - name: Upload feeds artifact
        uses: actions/upload-artifact@v4
        with:
          name: feeds
          path: temp-feeds.xml
        if: failure()
